config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:new]
  resources :posts
  resources :categories, only: [:show]
  # get 'posts/new', to: 'posts#new', as: "new_post"
  # post 'posts', to: 'posts#create'
  # get 'posts/:id', to: 'posts#show', as: "post"


  root to: 'static#index'
  get '/about', to: 'static#about', as: "about"
  get '/signup', to: 'users#new', as: "sign_up"
  get '/login', to: 'sessions#new', as: "login"
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/Post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 255}



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 255}
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :post_categories
  has_many :posts, through: :post_categories
  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 25}


end

app/models/post_category.rb
class PostCategory < ApplicationRecord

  belongs_to :category
  belongs_to :post

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  before_save { self.email = email.downcase }
  validates :first_name, :last_name, presence: true
  validates :username, presence: true, uniqueness: true, length: { in: 4..15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true, length: { in: 6...20 }, allow_nil: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?


private

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_current_post, only: [:edit, :update, :show, :destroy]

  def index
    @posts = Post.all
    render :index
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:sucess] = "Post was successfully created"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post was successfully updated"
      redirect_to @post
    else
      render :edit
    end
  end

    def destroy
        @post.delete
      flash[:danger] = "Post was successfully deleted"
      redirect_to "/posts"
    end

  private

  def set_current_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, category_ids: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      flash[:success] = "You have successfully logged in"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :set_current_user, only: [:edit, :update, :show, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Thoughful Blog #{@user.first_name}"
      session[:user_id] = @user.id
      redirect_to user_url(@user)
    else
      redirect_to sign_up_path
    end
  end

  def show
    @posts = @user.posts
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your information was successfully updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def index
    @users = User.all
  end

  def destroy
  end

  private

  def set_current_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :first_name, :last_name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/show.html.erb
<div class ="container">
<h4 align="center"> <%= @category.name.upcase %> </h4>
<% if !@category.posts.empty? %>
  <% @category.posts.each do |post| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="post-title">
            <%= link_to post.title, post_path(post) %>
          </div>
          <div class="post-body">
            <%= truncate(post.description, length: 100) %>
            <div class="post-meta-details">
              <small>Created by: <%= post.user.username if post.user%>,
                <%= time_ago_in_words(post.created_at) %> ago, last updated: <%= time_ago_in_words(post.updated_at) %> ago
              </small>
            </div>
          </div>
          <% if post.categories.any? %>
            <p>Categories: <%= render post.categories %></p>
          <% end %>
          <% if post.user == current_user %>
            <div class="post-actions">
              <%= link_to "Edit this post", edit_post_path(post), class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete this post", post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete the post?"}, class: "btn btn-xs btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <h4> There are not posts in this category </h4>
<% end %>

app/views/layouts/_footer.html.erb
<div class="containter">
  <footer class="footer">
    <small>
      Built by Joshua Pann | <a href="mailto:josh.pann@gmail.com" target="_top"> Contact </a> | <a href="https://github.com/jmpann"> GitHub</a> | <a href="https://medium.com/@josh.pann"> Medium</a> | <a href="http://www.linkedin.com/in/joshua-pann"> LinkendIn</a>
    </small>
    <nav>
      <ul>
        <li> <%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-default">
      <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Thoughtful Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Posts", posts_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <%if logged_in? %>
          <li><%= link_to "Create a Post", new_post_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">All Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category)%></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%=link_to "Logout", logout_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Your Posts", user_path(current_user) %></li>
              <li><%= link_to "Edit Your Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Create a Post", new_post_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%=link_to "Login", login_path %></li>
          <li><%=link_to "Sign Up", sign_up_path %></li>
        <%end%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThoughtfulBlogs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class= "container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj:@post %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@post, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of post", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of post" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to posts", posts_path %> ]
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 align="center"> Edit Post: <%=@post.title%></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 align="center">All Posts</h1>

<% @posts.each do |post| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="post-title">
          <%= link_to post.title, post_path(post) %>
        </div>
        <div class="post-body">
          <%= truncate(post.description, length: 100) %>
          <div class="post-meta-details">
            <small>Created by: <%= post.user.username if post.user%>,
              <%= time_ago_in_words(post.created_at) %> ago, last updated: <%= time_ago_in_words(post.updated_at) %> ago
            </small>
          </div>
        </div>
        <% if post.categories.any? %>
          <p>Categories: <%= render post.categories %></p>
        <% end %>
        <% if post.user == current_user %>
          <div class="post-actions">
            <%= link_to "Edit this post", edit_post_path(post), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this post", post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete the post?"}, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1 align="center"> Create a Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class ="container">

<h2 align="center">Title: <%= @post.title %></h2>
  <div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center description"><strong>Body:</strong></h4>
    <%= simple_format(@post.description) %>
  </br>
  <p>Written by: <%= @post.user.first_name%></p>
    <% if @post.categories.any? %>
      <p>Categories: <%= render @post.categories %></p>
    <% end %>
    <div class="post-actions">
      <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete the post?"}, class: "btn btn-xs btn-danger" %>
      <%= link_to "View all posts", posts_path, class: "btn btn-xs btn-success" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this post from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj:@user %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "ex: ssmith" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :email, class: "form-control", placeholder: "steve.smith@example.com" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :first_name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :first_name, class: "form-control", placeholder: "Steve" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :last_name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :last_name, class: "form-control", placeholder: "Smith" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control"%>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password_confirmation %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password_confirmation, class: "form-control"%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Thoughtful Bloggers</h1>
<div align="center">
  <% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="post-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li><small><%= pluralize(user.posts.count, "post") if user.posts %></small></li>
      </div>
    </div>
  </ul>
  <% end %>
  </div>

app/views/users/new.html.erb
<h1 align="center"> Sign Up for Thoughful Blog</h1>
  <%= render 'shared/errors', obj: @user %>

  <%= render 'form' %>

app/views/users/show.html.erb
<% if current_user == @user %>
  <h2 align="center">Welcome <%= @user.first_name %></h2>
<% else %>
   <h2 align="center"> <%=@user.first_name%>'s blog posts</h2>
 <% end %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
      <%= gravatar_for @user, size: 150 %>
    </div>
  </div>
</br>
    <div class="post-actions">
      <% @posts.each do |post| %>
        <div class="row">
          <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
              <div class="post-title">
                <%= link_to post.title, post_path(post) %>
              </div>
              <div class="post-body">
                <%= truncate(post.description, length: 100) %>
              </div>
              <% if post.categories.any? %>
                <p>Categories: <%= render post.categories %></p>
              <% end %>
              <div class="post-actions">
                <% if current_user == @user %>
                  <%= link_to "Edit this post", edit_post_path(post), class: "btn btn-xs btn-primary" %>
                  <%= link_to "Delete this post", post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete the post?"}, class: "btn btn-xs btn-danger" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>